#!/usr/bin/env python3
"""Generate the 2026 seed + parity fixtures from the source Excel template.

Reads the Hybrid Attendance Modeler template and emits:
  - packages/shared/src/seed/2026.json          (app seed: weekStart, days, meetup)
  - packages/shared/src/__fixtures__/template-2026.json  (parity oracle: officeDays,
    dtoDays, beltCached straight from Excel's recalculated values)

The template lives outside the repo (Kyle's OneDrive). This script is provenance:
re-run it if the template changes. Requires openpyxl (`python3 -m pip install openpyxl`).

Meetup weeks are detected from column-A fill (theme 5 = accent2 / orange in the template),
which matches chatgpm/cycles.yaml meet_week_start values (C2-C6) plus C1 (2026-01-12).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import openpyxl
from openpyxl.worksheet.formula import ArrayFormula

TEMPLATE = os.environ.get(
    "RTO_TEMPLATE",
    str(Path.home() / "Library/CloudStorage/OneDrive-Microsoft/Hybrid Attendance Modeler Template (2026).xlsx"),
)
HERE = Path(__file__).resolve().parents[1]  # packages/shared
DAY_KEYS = ["mon", "tue", "wed", "thu", "fri"]


def render_seed_ts(year: int, weeks: list[dict]) -> str:
    """Emit the seed as a typed TS module so tsc compiles it into dist (no JSON-emit gap)."""
    body = json.dumps({"year": year, "weeks": weeks}, indent=2)
    return (
        "// AUTO-GENERATED by scripts/generate-seed.py — do not edit by hand.\n"
        "// Default dataset for the year, transcribed from the Excel template.\n"
        "import type { YearData } from '../types.js';\n\n"
        f"export const SEED_{year}: YearData = {body};\n"
    )


def belt_oracle(seq: list[int]) -> list[float | None]:
    """Independent BELT oracle, mirroring the literal Excel array formula
    =(AVERAGE(LARGE(H[i-11]:H[i],{1..8})))/5. Written separately from the TS code."""
    out: list[float | None] = []
    for i in range(len(seq)):
        if i < 12:
            out.append(None)
            continue
        window = seq[i - 11 : i + 1]  # 12 values, indices i-11..i
        best = sorted(window, reverse=True)[:8]
        out.append(sum(best) / 8 / 5)
    return out


def build_parity() -> dict:
    """Rich varied office-day sequences + expected BELT, to pin top-8 selection semantics."""
    n = 52
    seqs = {
        "varied-mod6": [((i * 7 + 3) % 6) for i in range(n)],
        "constant-3": [3] * n,
        "alternating-5-0": [5 if i % 2 == 0 else 0 for i in range(n)],
        "ramp-0-5": [i % 6 for i in range(n)],
        "front-loaded": [5] * 12 + [1] * (n - 12),
    }
    scenarios = [
        {"name": name, "officeDays": seq, "expectedBelt": belt_oracle(seq)}
        for name, seq in seqs.items()
    ]
    return {"window": 12, "best": 8, "divisor": 5, "firstIndex": 12, "scenarios": scenarios}



def main() -> None:
    wb = openpyxl.load_workbook(TEMPLATE, data_only=False)
    wbv = openpyxl.load_workbook(TEMPLATE, data_only=True)
    ws, wv = wb["Tracker"], wbv["Tracker"]

    seed_weeks: list[dict] = []
    fixture_weeks: list[dict] = []

    # Data rows are 5..56 (row 57 is the Total row).
    for r in range(5, 57):
        date_cell = ws.cell(r, 1).value
        if date_cell is None:
            continue
        week_start = date_cell.date().isoformat()

        days = {k: (ws.cell(r, 2 + i).value or "Planned") for i, k in enumerate(DAY_KEYS)}

        # Meetup week = orange fill on the week cell (theme 5 / accent2).
        fill = ws.cell(r, 1).fill
        fg = fill.fgColor if fill and fill.patternType else None
        meetup = bool(fg is not None and fg.type == "theme" and fg.theme == 5)

        seed_weeks.append({"weekStart": week_start, "days": days, "meetup": meetup})

        office = wv.cell(r, 8).value  # H: Office Days (cached)
        dto = wv.cell(r, 7).value     # G: DTO Days (cached)
        belt_cell = wv.cell(r, 9).value  # I: BELT Average (cached)
        belt = None if isinstance(belt_cell, (ArrayFormula, str)) else belt_cell
        fixture_weeks.append(
            {
                "weekStart": week_start,
                "officeDays": int(office) if office is not None else 0,
                "dtoDays": int(dto) if dto is not None else 0,
                "beltCached": belt,
            }
        )

    # App seed as a typed TS module (compiled to dist by tsc; consumed by web + server).
    seed_path = HERE / "src/seed/2026.ts"
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    seed_path.write_text(render_seed_ts(2026, seed_weeks))

    # Excel-authoritative golden fixture (officeDays / dtoDays / beltCached) for parity tests.
    fix_path = HERE / "src/__fixtures__/template-2026.json"
    fix_path.parent.mkdir(parents=True, exist_ok=True)
    fix_path.write_text(json.dumps({"year": 2026, "weeks": fixture_weeks}, indent=2) + "\n")

    # Independent oracle over rich varied sequences (pins top-8 selection semantics).
    par_path = HERE / "src/__fixtures__/belt-parity.json"
    par_path.write_text(json.dumps(build_parity(), indent=2) + "\n")

    meetups = [w["weekStart"] for w in seed_weeks if w["meetup"]]
    scored = [w for w in fixture_weeks if w["beltCached"] is not None]
    print(f"wrote {seed_path.relative_to(HERE)} ({len(seed_weeks)} weeks)")
    print(f"wrote {fix_path.relative_to(HERE)} ({len(scored)} Excel-scored weeks)")
    print(f"wrote {par_path.relative_to(HERE)} (5 parity scenarios)")
    print(f"meetup weeks: {meetups}")


if __name__ == "__main__":
    main()
