// AUTO-GENERATED by scripts/generate-seed.py — do not edit by hand.
// Default dataset for the year, transcribed from the Excel template.
import type { YearData } from '../types.js';

export const SEED_2026: YearData = {
  "year": 2026,
  "weeks": [
    {
      "weekStart": "2026-01-05",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-01-12",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": true
    },
    {
      "weekStart": "2026-01-19",
      "days": {
        "mon": "Holiday",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-01-26",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-02-02",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-02-09",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-02-16",
      "days": {
        "mon": "Holiday",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-02-23",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-03-02",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-03-09",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": true
    },
    {
      "weekStart": "2026-03-16",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-03-23",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-03-30",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-04-06",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-04-13",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-04-20",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-04-27",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-05-04",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-05-11",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": true
    },
    {
      "weekStart": "2026-05-18",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-05-25",
      "days": {
        "mon": "Holiday",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-06-01",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-06-08",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-06-15",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-06-22",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-06-29",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Holiday"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-07-06",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-07-13",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": true
    },
    {
      "weekStart": "2026-07-20",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-07-27",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-08-03",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-08-10",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-08-17",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-08-24",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-08-31",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-09-07",
      "days": {
        "mon": "Holiday",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-09-14",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-09-21",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": true
    },
    {
      "weekStart": "2026-09-28",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-10-05",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-10-12",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-10-19",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-10-26",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-11-02",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-11-09",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-11-16",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": true
    },
    {
      "weekStart": "2026-11-23",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Holiday",
        "fri": "Holiday"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-11-30",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-12-07",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-12-14",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Planned"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-12-21",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Holiday",
        "fri": "Holiday"
      },
      "meetup": false
    },
    {
      "weekStart": "2026-12-28",
      "days": {
        "mon": "Planned",
        "tue": "Planned",
        "wed": "Planned",
        "thu": "Planned",
        "fri": "Holiday"
      },
      "meetup": false
    }
  ]
};
